#
# Travis CI recipe to build, test and push docker images to the Docker Hub.
#

language: generic

os:
  - linux

services:
  - docker

git:
  submodules: true

env:
  global:
  - DOCKER_REPO=christopher102994
  - DOCKER_NAME=docker-base-img-gui
jobs:
  include:
  - stage: Alpine Container
    env: 
    - DOCKER_FILE=Dockerfile.alpine 
    - BASE_IMAGE=christopher102994/docker-base-img:alpine-3.10
    - IMAGE_TAG=alpine-3.10
    script: tools/scripts/make_container.sh
    deploy:
        provider: script
        script: tools/scripts/push_to_registry.sh
        
  - stage: Debian Container
    env: 
      - DOCKER_FILE=Dockerfile.debian 
      - BASE_IMAGE=christopher102994/docker-base-img:debian-10
      - IMAGE_TAG=debian-10
    script: tools/scripts/make_container.sh
    deploy:
        provider: script
        script: tools/scripts/push_to_registry.sh

  - stage: Ubuntu Container
    env: 
    - DOCKER_FILE=Dockerfile.debian 
    - BASE_IMAGE=christopher102994/docker-base-img:ubuntu-bionic
    - IMAGE_TAG=ubuntu-bionic
    script: tools/scripts/make_container.sh
    deploy:
        provider: script
        script: tools/scripts/push_to_registry.sh
