#!/usr/bin/with-contenv bash

set -u # Unset Variables are an error
set -e # Exit on error

# Check process and kill if running.
check_and_terminate_process 'openbox'

# This wait's for the notification-fd file to be updated before executing.
s6-svwait -t 10000 -U /var/run/s6/services/xvfb

# Openbox homedir is HOME.
export HOME=/config
export DISPLAY=$DISPLAY
export USER=$USERNAME

log "openbox" "Starting . . ."
# This executes and notifies the notification-fd file so further processes can start.
exec 2>&1 	/bin/s6-notifyoncheck -d -w 500 \
			s6-setuidgid "${PUID}":"${PGID}" \
			/usr/bin/openbox-session \
			> /dev/null 2>&1