#!/usr/bin/with-contenv bash

set -u # Unset Variables are an error
set -e # Exit on error

# Check process and kill if running.
check_and_terminate_process 'tint2'

# This wait's for the notification-fd file to be updated before executing.
s6-svwait -t 10000 -U /var/run/s6/services/openbox

echo 'Starting tint2 . . .'
# This executes and notifies the notification-fd file so further processes can start.
exec 2>&1 	/bin/s6-notifyoncheck -d -w 500 \
			s6-setuidgid 900:900 \
			/usr/bin/tint2 -c /etc/xdg/tint2/tint2rc \
		 	> /dev/null 2>&1