#!/usr/bin/with-contenv sh

set -u # Unset Variables are an error
set -e # Exit on error

ROOT_FILE="/root/.vncpass"

# If VNC_PASSWORD is set then we will turn it into a password. Else delete it.
if [ "${VNC_PASSWORD:-UNSET}" != "UNSET" ]; then
	/usr/bin/x11vnc -storepasswd "$VNC_PASSWORD" $ROOT_FILE
else
	rm -f $ROOT_FILE
fi


[ -f "$ROOT_FILE" ] && chmod 400 $ROOT_FILE

return 0