#!/usr/bin/with-contenv bash

set -u # Unset Variables are an error
set -e # Exit on error

# Check process and kill if running.
check_and_terminate_process 'x11vnc'

# VNC Password
ROOT_FILE="/root/.vncpass"
if [ -f "$ROOT_FILE" ] && [ -s "$ROOT_FILE" ]; then
	VNC_PASS="-rfbauth $ROOT_FILE"
else
	VNC_PASS="-nopw"
fi

# This wait's for the notification-fd file to be updated before executing.
s6-svwait -t 10000 -U /var/run/s6/services/xvfb


# Ensure Log folder exists
if [ ! -d '/config/log/x11vnc' ]; then
	mkdir -p /config/log/x11vnc
fi

chown -R $PUID:$PGID /config/log/x11vnc
chmod -R 0755 /config/log/x11vnc

log "x11vnc" "Starting . . ."
# This executes and notifies the notification-fd file so further processes can start.
exec 2>&1 	/bin/s6-notifyoncheck -d -w 500 \
			/usr/bin/x11vnc \
			-o /config/log/x11vnc/x11vnc.log \
			-display $DISPLAY \
			-desktop "${APP_NAME:-Docker Base GUI}" \
			$VNC_PASS \
			-cursor arrow \
			-repeat \
			-shared \
			-forever \
			-noxrecord \
			> /dev/null 2>&1




